version: '3'

services:
  fastapi:
    container_name: quiz_api
    build:
      context: .
      dockerfile: Dockerfile

    command: [ "/fastapi_app/cmd.sh" ]
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_DB=quizdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

networks:
    postgres:
      driver: bridge

volumes:
  pgdbdata: null