version: '3'

services:
  fastapi:
    container_name: quiz_api
    build:
      context: .
      dockerfile: Dockerfile

    command: [ "/fastapi_app/cmd.sh" ]
    ports:
      - "8000:8000"
    depends_on:
      pgdb:
        condition: service_healthy
    volumes:
      - .:/fastapi_app

  pgdb:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb_quiz
    volumes:
      - ./database:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  pgdbdata: null