"""question_id

Revision ID: 0184bab8f875
Revises: 6441633f65da
Create Date: 2023-05-18 16:54:00.841765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0184bab8f875'
down_revision = '6441633f65da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_id')
    # ### end Alembic commands ###
